Yonetimsell/Yonetimsell.UI/Areas/Customer/Controllers/TeamMemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Yonetimsell.Business.Abstract;
using Yonetimsell.Entity.Concrete.Identity;
using Yonetimsell.Shared.ComplexTypes;
using Yonetimsell.Shared.Helpers.Abstract;
using Yonetimsell.Shared.ViewModels.TeamMemberViewModels;

namespace Yonetimsell.UI.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class TeamMemberController : Controller
    {
        private readonly ITeamMemberService _teamMemberManager;
        private readonly IFriendshipService _friendshipManager;
        private readonly UserManager<User> _userManager;
        private readonly ISweetAlertService _sweetAlert;
        private readonly ISubscriptionService _subscriptionManager;

        public TeamMemberController(ITeamMemberService teamMemberManager, IFriendshipService friendshipManager, UserManager<User> userManager, ISweetAlertService sweetAlert, ISubscriptionService subscriptionManager)
        {
            _teamMemberManager = teamMemberManager;
            _friendshipManager = friendshipManager;
            _userManager = userManager;
            _sweetAlert = sweetAlert;
            _subscriptionManager = subscriptionManager;
        }
        [HttpGet]
        public async Task<IActionResult> AddTeamMember(int projectId)
        {
            var userId = _userManager.GetUserId(User);
            var response = await _friendshipManager.GetFriendListAsync(userId);
            var friendList = response.Data;
            var teamMemberViewModel = new TeamMemberViewModel();
            teamMemberViewModel.ProjectId = projectId;
            teamMemberViewModel.UserId = userId;
            var result = new AddTeamMemberViewModel
            {
                TeamMemberViewModel = teamMemberViewModel,
                Friendships = friendList,
                CurrentUserId = userId
            };
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> AddTeamMember(string userId, int projectId, ProjectRole projectRole, string currentUserId)
        {
            var checkResponse = await _teamMemberManager.CheckIfExistsAsync(userId, projectId);
            var SubscriptionResponse = await _subscriptionManager.GetActiveAsync(userId);
            var teamMemberCount = await _teamMemberManager.TeamMemberCountAsync(projectId);
            if (!SubscriptionResponse.IsSucceeded && teamMemberCount.Data > 2)
            {
                TempData["TeamMemberToast"] = _sweetAlert.MiddleNotification("warning", "Mevcut planınıza göre 3ten fazla takım arkadaşı ekleyemezsiniz!");
                return RedirectToAction("AddTeamMember", new { projectId });
            }
            if (checkResponse.Data)
            {
                TempData["TeamMemberToast"] = _sweetAlert.MiddleNotification("error", "Kullanıcı zaten takım arkadaşınız!");
                return RedirectToAction("AddTeamMember", new { projectId });
            }
            var teamMemberViewModel = new TeamMemberViewModel
            {
                UserId = userId,
                ProjectId = projectId,
                ProjectRole = projectRole
            };
            var response = await _teamMemberManager.AddUserToProjectAsync(teamMemberViewModel);
            if (response.IsSucceeded)
            {
                TempData["TeamMemberToast"] = _sweetAlert.MiddleNotification("success", "Kullanıcı takım arkadaşlarına eklendi");
                return RedirectToAction("Detail", "Project", new { projectId });
            }
            else
            {
                TempData["TeamMemberToast"] = _sweetAlert.MiddleNotification("error", "Kullanıcı takım arkadaşlarına eklenemedi!");
                return RedirectToAction("AddTeamMember", new { projectId });
            }
        }
        public async Task<IActionResult> RemoveTeamMember(int id)
        {
            var response = await _teamMemberManager.GetTeamMemberByIdAsync(id);
            var projectId = response.Data.ProjectId;
            await _teamMemberManager.RemoveUserFromProjectAsync(id);
            return Redirect($"/Customer/Project/Detail?projectId={projectId}");
        }

    }
}

Yonetimsell/Yonetimsell.UI/Areas/Customer/Views/TeamMember/AddTeamMember.cshtml
@model AddTeamMemberViewModel

<div class="container-fluid pt-4 px-4 h-100">
    <div class="bg-light text-center rounded p-4">
        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0 display-6">Arkadaş Listesi</h6>
        </div>
        <div class="table-responsive">
            <table id="myDataTable" class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-dark">
                        <th scope="col">Kullanıcı Adı</th>
                        <th scope="col">Proje Rolü</th>
                        <th scope="col">#</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.Friendships)
                    {
                        <tr>
                            @{
                                string resultId;
                                string resultName;
                                if (Model.CurrentUserId == user.SenderUserId)
                                {
                                    resultId = user.ReceiverUserId;
                                    resultName = user.ReceiverUserName;
                                }
                                else if (Model.CurrentUserId == user.ReceiverUserId)
                                {
                                    resultId = user.SenderUserId;
                                    resultName = user.SenderUserName;
                                }
                                else
                                {
                                    resultId = "Kullanıcı id bulunamadı";
                                    resultName = "Kullanıcı Bulunamadı";
                                }
                            }
                            <form asp-area="Customer" asp-controller="TeamMember" asp-action="AddTeamMember" method="post">
                            <td>@resultName</td>
                            <td>
                                <select name="ProjectRole" class="form-select form-select-sm mb-3">
                                    <option value="0">Proje Yöneticisi</option>
                                    <option value="1">Geliştirici</option>
                                    <option value="2">Testçi</option>
                                    <option value="3">Analist</option>
                                    <option value="4">Tasarımcı</option>
                                </select>
                            </td>
                            <td>
                                <input type="hidden" name="UserId" value="@resultId" />
                                <input type="hidden" name="ProjectId" value="@Model.TeamMemberViewModel.ProjectId" />
                                <input type="hidden" name="CurrentUserId" value="@Model.CurrentUserId" />
                                <button type="submit" class="btn btn-success">Ekle</button>
                            </td>
                            </form>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>